## Chapter 2

# Theory

1. I kapitlet beskrivs en checklista med sju steg. Beskriv de sju stegen över-
siktligt. I verkligheten, följs dessa steg i en rak progression eller arbetar man generellt sett mer iterativt?

    1. Define the problem
    2. Access the data
    3. Perform an exploratory data analysis, used to determine if ML is needed, and discover potential paterns which may be useful when managing the data in the subsequent step.
    4. Process the data. Decide which columns and datapoints are useful for training, as well as how to manage missing data and outliers.
    5. Train the ML model. Decide on the most suitable model, hyperparameters, and perform the training.
    6. Present your results of the model.
    7. Put the model into production.

2. Vad menas med att en modell produktionssätts?

That the model is in a stage where it is being used for its intended purpose. It may still be improved iteratively in some cases.

3. Vad är scikit-learn för något? Biblioteket följer några centrala designprin-
ciper. Vilka är dessa? Vad är estimators, predictors och transformers?

It's a data-analysis library, which provides functions for machine learning.
The scikit estimator is the object used for learning from data, while a predictor is a specific estimator, which can use the estimation to perform prediction. A transformer is an estimator which modifies the input data.

4. Vad är TensorFlow och Keras?

Tensorflow is another ML library, while Keras is an API for TensorFlow

5. Kalle och Stina diskuterar maskininlärning över en lunch. Kalle säger “om
jag tränat en modell och den inte presterar bra nog på testdatan så justerar
jag den tills den gör det.” Stina säger “det är ett stort fel att göra så, det
enda du då åstadkommer är att du överanpassar testdatan. Hela syftet
med testdatan försvinner då”. Vad säger du om deras dialog?

Since the model is not being trained on the test-data, modifying the hyperparameters and changing which training model used until you have one which is better at predicting the test-data is very logical. Stina does however also have a point that there can potentially be a bias towards specifically the test-data, if it is being adjusted specifically for it, which a reason for why we typically leave a section of the data to be used for validation, before being tested on the test-data.

6. Många AI/ML projekt uppnår inte de ursprungligen satta målen eller att
ens passera någon form av prototyp-stadie. Vad tror du detta beror på och
hur ska vi förhålla oss till det?

There can be several reasons, one reason being that the Exploratory Data Analysis shows that the desired analysis can be performed through standard data analysis. Besides this, a ML model not reaching the desired results can be caused by bad or incomplete data, insufficient models, insufficient skills, or funds, etc. The failure emerging when the goal is is incompatible with the reality of the environment and factors the model is being developed in.
What needs to be done to relate to this is to keep the low rate of success in mind before undertaking a venture using ML, and keep in mind existing limitations at the start of the project.

# Code

7. Gå igenom samtliga kodexempel i kapitlet och skriv gärna av koden ma-
nuellt. Det är även bra att experimentera genom att ändra vissa delar av
koden och läsa dokumentationen.

Hashtag thumbs up

8. Förklara vad koden nedan gör. Varför är det viktigt att kunna spara en
modell?

In [1]:
#from sklearn.datasets import make_regression
#from sklearn.linear_model import LinearRegression
#from joblib import dump, load

#X, y = make_regression(n_samples=20000, n_features=3,
#noise=0.1)↪
#model = LinearRegression().fit(X, y)
#dump(model, "linear_model.joblib")
#model_loaded = load("linear_model.joblib")
#print(model_loaded.predict(X[:5])

We dump and then load the model using joblib, providing the model object, then loading the saved model to a new object.
This is done to prevent needing to retrain the model each time we want to make use of it.

9. Denna uppgift består av flera steg enligt nedan.

a) Läs in datasetet “data_01.csv” med funktionen read_csv() från Pandas. Funktionen returnerar en DataFrame.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import root_mean_squared_error, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split

dataset = pd.read_csv(r'C:data_01.csv')

dataset.head()

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

b) Dela upp datasetet i X och y.

In [3]:
X = dataset.drop(columns=['target'])
y = dataset['target']

print(y.head())
print(X.head())

0    220.173943
1    175.873929
2   -162.270054
3    165.930461
4     43.250511
Name: target, dtype: float64
         x1        x2        x3        x4        x5
0  0.743487  1.072825  1.332911 -1.244771  0.344978
1  0.835264  0.202184  0.966480  0.745883 -0.033773
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224
3  1.210186  1.685258 -0.394123  0.719024 -2.166585
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473

c) Dela upp datan ytterligare, i ett träning-, ett validering-, och ett testsetmed train_test_split(). Låt 20% av datan vara testdata och 15% av den återstående datan vara valideringsdata.

In [4]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=30)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.15, random_state=26)

print(X_train.shape)
print(y_train.shape)

(135, 5)
(135,)

d) Träna två valfria regressionsmodeller (exempelvis LinearRegression och DecisionTreeRegressor) på träningsdatan. Notera, i kapitel 3 kommer vi lära oss mer om DecisionTreeRegressor.

In [5]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
lin_reg_pred = lin_reg.predict(X_val)

In [6]:
tree_reg = DecisionTreeRegressor(random_state=42)

# Find the best hyperparameter through GridSearch.
hyper_params = {'max_depth': (None, 1, 2, 3, 5, 10)}
reg = GridSearchCV(
    tree_reg,
    hyper_params,
    scoring='neg_root_mean_squared_error',
    cv=5
)

reg.fit(X_train, y_train)
tree_reg_pred = reg.predict(X_val)

In [7]:
print(reg.best_params_)
pd.DataFrame(reg.cv_results_)

{'max_depth': 10}

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009610,0.001776,0.006114,0.001653,None,{'max_depth': None},-97.510952,-110.668896,-93.924165,-106.597294,-75.152327,-96.770727,12.375189,3
1,0.006372,0.001307,0.005074,0.000904,1,{'max_depth': 1},-90.512857,-123.475654,-132.234844,-106.245798,-115.938319,-113.681494,14.403617,6
2,0.007222,0.001580,0.006266,0.001639,2,{'max_depth': 2},-99.990635,-102.085267,-133.703115,-116.618343,-105.650863,-111.609645,12.445326,5
3,0.006979,0.001448,0.004672,0.001078,3,{'max_depth': 3},-110.659004,-100.888021,-107.641872,-112.667157,-104.862398,-107.343690,4.177368,4
4,0.007233,0.001471,0.005095,0.000817,5,{'max_depth': 5},-86.078501,-103.864217,-95.529089,-98.757113,-87.437304,-94.333245,6.745886,2
5,0.008121,0.002587,0.005752,0.000895,10,{'max_depth': 10},-88.119807,-95.324441,-91.259805,-106.974609,-74.910516,-91.317835,10.398253,1

e) Utvärdera modellerna på valideringsdatan.

In [8]:
def regression_metrics(y_true, y_pred):
    return {
        'MAE': mean_absolute_error(y_true, y_pred),
        'RMSE': np.sqrt(mean_squared_error(y_true, y_pred))
    }

validation_results = pd.DataFrame({
    'Linear Regression': regression_metrics(y_val, lin_reg_pred),
    'Decision Tree': regression_metrics(y_val, tree_reg_pred)
}).T

validation_results

                         MAE       RMSE
Linear Regression   2.798756   3.814371
Decision Tree      68.830817  88.511555

f) Träna om den bäst presterande modellen på både tränings- och validerings-datan.

In [9]:
lin_reg_final = LinearRegression().fit(X_train_full, y_train_full)
pred_test = lin_reg_final.predict(X_test)

g) Utvärdera modellen på testdatan.

In [10]:
test_results = pd.Series(
    regression_metrics(y_test, pred_test),
    name='Test set'
)
test_results

MAE     2.289200
RMSE    2.976922
Name: Test set, dtype: float64

h) Träna om modellen på hela datasetet.

In [11]:
lin_reg_final = LinearRegression().fit(X, y)

10. Datasetet “salary_dataset.csv” innehåller 29 observationer av personer. YearsExperience är hur många år de arbetat, och Salary är deras lön.

a) Läs in datasetet “salary_dataset.csv” med pandas read_csv()-funktion och dela upp i X och y. Avgör själv vilken variabel som ska vara den beroende variabeln y.

In [19]:
salaryDataset = pd.read_csv(r'C:salary_dataset.csv')

salaryDataset.head()

   YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [20]:
Xsal = salaryDataset.drop(columns=['Salary'])
ysal = salaryDataset['Salary']

print(ysal.head())
print(Xsal.head())

0    39344.0
1    46206.0
2    37732.0
3    43526.0
4    39892.0
Name: Salary, dtype: float64
   YearsExperience
0              1.2
1              1.4
2              1.6
3              2.1
4              2.3

b) Dela upp datasetet i träning- och testset. (Inget validerings-set alltså!)

In [21]:
X_sal_train, X_sal_test, y_sal_train, y_sal_test = train_test_split(Xsal, ysal, test_size=0.2, random_state=30)

print(X_sal_train.shape)
print(y_sal_train.shape)

(24, 1)
(24,)

c) Träna två regressionsmodeller med k-delad korsvalidering med cross_validate()-funktionen från scikit-learn. Använd neg_root_mean_squared_error som scoring. Välj själv hur många iterationer den ska göra genom hyperparametern cv.

In [22]:
lin_reg_sal = LinearRegression()
lin_reg_sal.fit(X_sal_train, y_sal_train)
lin_reg_sal_pred = lin_reg_sal.predict(X_sal_test)

In [24]:
tree_reg_sal = DecisionTreeRegressor(random_state=42)

reg_sal = GridSearchCV(
    tree_reg_sal,
    hyper_params,
    scoring='neg_root_mean_squared_error',
    cv=5
)

reg_sal.fit(X_sal_train, y_sal_train)
tree_reg_pred_sal = reg_sal.predict(X_sal_test)

In [25]:
print(reg_sal.best_params_)
pd.DataFrame(reg_sal.cv_results_)

{'max_depth': 3}

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006583,0.001318,0.003701,0.000798,None,{'max_depth': None},-5943.221315,-11314.236925,-9177.342962,-6981.188867,-9054.180019,-8494.034018,1872.408342,3
1,0.004010,0.000917,0.002918,0.000769,1,{'max_depth': 1},-8785.028482,-20487.612479,-14222.397739,-10684.464528,-15455.820553,-13927.064756,4060.051615,6
2,0.004079,0.001112,0.002864,0.000681,2,{'max_depth': 2},-5708.820440,-13485.184668,-10880.483520,-6697.867177,-9616.422446,-9277.755650,2820.603263,5
3,0.004756,0.001083,0.002696,0.000324,3,{'max_depth': 3},-5228.650789,-10690.536109,-8225.255081,-6196.104761,-6381.531854,-7344.415719,1933.629969,1
4,0.003722,0.000410,0.003233,0.000257,5,{'max_depth': 5},-5945.711967,-11314.236925,-9177.342962,-6962.826754,-9007.316449,-8481.487012,1871.986551,2
5,0.004898,0.001234,0.003505,0.000848,10,{'max_depth': 10},-5943.221315,-11314.236925,-9177.342962,-6981.188867,-9054.180019,-8494.034018,1872.408342,3

d) Utvärdera modellen som presterar bäst på testsetet.

In [26]:
sal_validation_results = pd.DataFrame({
    'Linear Regression': regression_metrics(y_sal_test, lin_reg_sal_pred),
    'Decision Tree': regression_metrics(y_sal_test, tree_reg_pred_sal)
}).T

sal_validation_results

                           MAE         RMSE
Linear Regression  1941.804710  2335.286325
Decision Tree      3640.740741  4421.800345

Answer: Linear Regression

11. I denna uppgift kommer vi arbeta med kategorisk data. Nominaldata är
kategorisk data där kategorierna inte har någon inbördes rangordning.
Datasetet mpg som följer med biblioteket seaborn är ett dataset med
398 observationer av bilar. Den beroende variabeln mpg står för miles
per gallon och beskriver bilarnas bränsleeffektivitet.
Om vi vill träna en regressionsmodell på mpg-datasetet behöver vi
hantera de två kategoriska variablerna origin och name. Variabeln
origin är en kategorisk variabel med tre olika värden: europe, ja-
pan och usa. Den lämpar sig bra för one hot encoding. Variabeln
name har 305 unika värden. Skulle vi utföra one hot encoding på den
skulle vårt dataset få 305 nya dimensioner vilket inte är så lämpligt
i detta fall. Dessutom - tror du att namnet på bilen har något att gö-
ra med hur långt den kör på en gallon bensin? Vi ska därför droppa
name-kolumnen innan vi börjar träna en modell på datan.

a) Läs in datasetet mpg med seaborns load_dataset()-funktion.

In [28]:
import seaborn as sns
df = sns.load_dataset("mpg")
print(df.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

b&c) Droppa rader med saknade värden med dropna()-metoden. Droppa columnen 'name'

In [33]:
df_clean = df.dropna().drop(columns=['name'])
print(df_clean.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin
0          70    usa
1          70    usa
2          70    usa
3          70    usa
4          70    usa

d) Utför en dummy-variable-encoding på origin-kolumnen med pandas get_dummies()-funktion. Ange drop_first=True så att vi får 2 nya kolumner istället för 3.

In [34]:
df_encoded = pd.get_dummies(df_clean, dtype=int, drop_first=True)
print(df_encoded.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year  origin_japan  origin_usa
0          70             0           1
1          70             0           1
2          70             0           1
3          70             0           1
4          70             0           1

e) Dela upp datasetet i X och y, med mpg som den beroende variabeln y.

In [36]:
Xmpg = df_encoded.drop(columns=['mpg'])
ympg = df_encoded['mpg']

print(ympg.head())
print(Xmpg.head())

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64
   cylinders  displacement  horsepower  weight  acceleration  model_year  \
0          8         307.0       130.0    3504          12.0          70
1          8         350.0       165.0    3693          11.5          70
2          8         318.0       150.0    3436          11.0          70
3          8         304.0       150.0    3433          12.0          70
4          8         302.0       140.0    3449          10.5          70

   origin_japan  origin_usa
0             0           1
1             0           1
2             0           1
3             0           1
4             0           1

f) Dela upp datasetet i träning- och testset.

In [37]:
X_mpg_train, X_mpg_test, y_mpg_train, y_mpg_test = train_test_split(Xmpg, ympg, test_size=0.2, random_state=30)

print(X_mpg_train.shape)
print(y_mpg_train.shape)

(313, 8)
(313,)

g) Träna en linjär regressionsmodell på träningsdatan och utvärdera den på testdatan.

In [38]:
lin_reg_mpg = LinearRegression().fit(X_mpg_train, y_mpg_train)
pred_mpg = lin_reg_mpg.predict(X_mpg_test)

In [39]:
test_results = pd.Series(
    regression_metrics(y_mpg_test, pred_mpg),
    name='mpg set'
)
test_results

MAE     2.978759
RMSE    4.013055
Name: mpg set, dtype: float64